name: build
on: workflow_dispatch
jobs:
  build-services:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Build and push connector
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: itatm/atom:latest
